services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_DB_URL=${MONGO_DB_URL}
    ports:
      - ${SERVER_BIND_PORT:-8080}:${PORT:-8080}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    ports:
      - ${MONGO_BIND_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db
